
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b"<\xaf\x86\xd1\x10=\x7f\xca\xcf'lRa\xb7\xf2w"
    
_lr_action_items = {'FLUSH':([2,3,4,5,6,7,9,10,18,19,20,21,22,23,24,25,30,32,33,34,],[-12,-9,-17,13,-18,-19,-13,-21,-11,-20,-10,-6,29,-5,-7,-8,-14,-22,-4,-3,]),'MINUS':([2,3,4,5,6,7,9,10,17,18,19,20,24,25,26,30,32,35,],[-12,-9,-17,15,-18,-19,-13,-21,15,-11,-20,-10,-7,-8,15,-14,-22,15,]),'NAME':([0,8,11,12,13,14,15,16,29,31,],[6,6,6,6,21,6,6,6,33,6,]),'COMMA':([2,3,4,6,7,9,10,18,19,20,24,25,26,27,30,32,35,],[-12,-9,-17,-18,-19,-13,-21,-11,-20,-10,-7,-8,-16,31,-14,-22,-15,]),'LPAREN':([0,6,8,11,12,14,15,16,21,31,33,],[8,16,8,8,8,8,8,8,16,8,16,]),'TIMES':([2,3,4,6,7,9,10,18,19,20,24,25,30,32,],[-12,12,-17,-18,-19,-13,-21,-11,-20,-10,12,12,-14,-22,]),'NUMBER':([0,8,11,12,14,15,16,31,],[4,4,4,4,4,4,4,4,]),'$end':([1,2,3,4,5,6,7,9,10,18,19,20,21,22,23,24,25,30,32,33,34,],[0,-12,-9,-17,-2,-18,-19,-13,-21,-11,-20,-10,-6,-1,-5,-7,-8,-14,-22,-4,-3,]),'DIVIDE':([2,3,4,6,7,9,10,18,19,20,24,25,30,32,],[-12,11,-17,-18,-19,-13,-21,-11,-20,-10,11,11,-14,-22,]),'PLUS':([2,3,4,5,6,7,9,10,17,18,19,20,24,25,26,30,32,35,],[-12,-9,-17,14,-18,-19,-13,-21,14,-11,-20,-10,-7,-8,14,-14,-22,14,]),'RPAREN':([2,3,4,6,7,9,10,17,18,19,20,24,25,26,27,30,32,35,],[-12,-9,-17,-18,-19,-13,-21,28,-11,-20,-10,-7,-8,-16,30,-14,-22,-15,]),'EXCLAMATION':([2,4,6,7,9,10,18,19,20,28,30,32,],[10,-17,-18,-19,-20,-21,10,-20,10,32,-14,-22,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,8,16,31,],[5,17,26,35,]),'final':([0,],[1,]),'args':([16,],[27,]),'factor':([0,8,11,12,14,15,16,31,],[2,2,18,20,2,2,2,2,]),'func':([0,8,11,12,13,14,15,16,29,31,],[9,9,19,19,23,9,9,9,34,9,]),'filters':([13,],[22,]),'fat':([0,8,11,12,14,15,16,31,],[7,7,7,7,7,7,7,7,]),'term':([0,8,14,15,16,31,],[3,3,24,25,3,3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> final","S'",1,None,None,None),
  ('final -> expr FLUSH filters','final',3,'p_final','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',36),
  ('final -> expr','final',1,'p_final_simple','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',40),
  ('filters -> filters FLUSH func','filters',3,'p_filters','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',44),
  ('filters -> filters FLUSH NAME','filters',3,'p_filters','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',45),
  ('filters -> func','filters',1,'p_filters_simple','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',49),
  ('filters -> NAME','filters',1,'p_filters_simple','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',50),
  ('expr -> expr PLUS term','expr',3,'p_expr_plus','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',54),
  ('expr -> expr MINUS term','expr',3,'p_expr_minus','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',61),
  ('expr -> term','expr',1,'p_expr_term','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',68),
  ('term -> term TIMES factor','term',3,'p_term_mul','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',72),
  ('term -> term DIVIDE factor','term',3,'p_term_div','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',79),
  ('term -> factor','term',1,'p_term_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',83),
  ('term -> func','term',1,'p_term_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',84),
  ('func -> NAME LPAREN args RPAREN','func',4,'p_func','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',88),
  ('args -> args COMMA expr','args',3,'p_args_comma','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',95),
  ('args -> expr','args',1,'p_args_expr','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',104),
  ('factor -> NUMBER','factor',1,'p_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',108),
  ('factor -> NAME','factor',1,'p_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',109),
  ('factor -> fat','factor',1,'p_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',110),
  ('factor -> func','factor',1,'p_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',111),
  ('fat -> factor EXCLAMATION','fat',2,'p_fat_factor','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',115),
  ('fat -> LPAREN expr RPAREN EXCLAMATION','fat',4,'p_fat_group','/home/chips/.dropbox_files/Dropbox/projetos/pytex/src/pytex/alttex/var_command/parser.py',119),
]
